# ci fn production

trigger: none

pool:
  name: Azure Pipelines

variables:
  buildConfiguration: 'Release'
  
steps:
- checkout: self

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'build'
    projects: '**/BinusSchool.Attendance.FnAttendance.FrontEndAPI.csproj'
    arguments: '-c Release'